notifications:
  email: false

rvm:
  - 2.1.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: xvfb-run bundle exec rspec spec