# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Embed::Purl::MediaFile do
  describe '#label_or_filename' do
    subject { resource_file.label_or_filename }

    context 'with audio caption' do
      let(:resource_file) { build(:media_file, :caption) }

      it { is_expected.to eq 'English captions' }
    end

    context 'with auto generated caption' do
      let(:resource_file) { build(:media_file, :autogenerated_media_transcript) }

      it { is_expected.to eq 'English captions (auto-generated)' }
    end

    context 'with audio transcript' do
      let(:resource_file) { build(:media_file, :media_transcript) }

      it { is_expected.to eq 'English transcript' }
    end
  end
end
